version: '3.8'
services:

  kitten-generator-api:
    container_name: kitten-generator-api
    image: kitten-generator-api
    networks:
      - realworldone
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://*:5000

  user-management-api:
    container_name: user-management-api
    image: user-management-api
    networks:
      - realworldone
    ports:
      - "5001:50001"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://*:5001
      
volumes:
  data:
    driver: local

networks:
  realworldone:
    driver: bridge
